// Theme definitions
export const themes = {
  random: "Random",
  clashroyale: "Clash Royale",
  fortnite: "Fortnite",
  teachers: "Teachers",
  animals: "Animals",
  food: "Food",
  movies: "Movies",
  sports: "Sports",
} as const;

export type ThemeKey = keyof typeof themes;

// Clash Royale themed pairs
export const clashRoyalePairs: [string, string][] = [
  ["princess", "crown"],
  ["giant", "tower"],
  ["wizard", "spell"],
  ["archer", "arrow"],
  ["knight", "sword"],
  ["barbarian", "rage"],
  ["goblin", "spear"],
  ["skeleton", "bone"],
  ["dragon", "fire"],
  ["balloon", "bomb"],
  ["minion", "swarm"],
  ["pekka", "armor"],
  ["hog", "hammer"],
  ["musketeer", "rifle"],
  ["valkyrie", "axe"],
  ["witch", "spell"],
  ["sparky", "charge"],
  ["lava", "hound"],
  ["mega", "knight"],
  ["bandit", "dash"],
];

// Fortnite themed pairs
export const fortnitePairs: [string, string][] = [
  ["battle", "royale"],
  ["storm", "circle"],
  ["chest", "loot"],
  ["weapon", "damage"],
  ["building", "material"],
  ["squad", "team"],
  ["elimination", "victory"],
  ["drop", "island"],
  ["zone", "safe"],
  ["health", "shield"],
  ["ammo", "reload"],
  ["sniper", "scope"],
  ["shotgun", "close"],
  ["assault", "rifle"],
  ["pistol", "sidearm"],
  ["grenade", "explosion"],
  ["medkit", "heal"],
  ["backpack", "inventory"],
  ["emote", "dance"],
  ["skin", "outfit"],
];

// Teachers themed pairs
export const teachersPairs: [string, string][] = [
  ["homework", "assignment"],
  ["test", "grade"],
  ["classroom", "desk"],
  ["chalkboard", "lesson"],
  ["textbook", "chapter"],
  ["pencil", "write"],
  ["eraser", "mistake"],
  ["ruler", "measure"],
  ["calculator", "math"],
  ["globe", "geography"],
  ["microscope", "science"],
  ["dictionary", "word"],
  ["backpack", "school"],
  ["lunch", "cafeteria"],
  ["recess", "playground"],
  ["detention", "punishment"],
  ["principal", "office"],
  ["library", "books"],
  ["gym", "exercise"],
  ["art", "creative"],
];

// Animals themed pairs
export const animalsPairs: [string, string][] = [
  ["lion", "roar"],
  ["elephant", "trunk"],
  ["giraffe", "neck"],
  ["zebra", "stripes"],
  ["monkey", "swing"],
  ["penguin", "slide"],
  ["dolphin", "jump"],
  ["whale", "spout"],
  ["shark", "fin"],
  ["octopus", "tentacle"],
  ["butterfly", "wings"],
  ["bee", "honey"],
  ["spider", "web"],
  ["snake", "slither"],
  ["frog", "hop"],
  ["rabbit", "carrot"],
  ["squirrel", "nut"],
  ["bear", "hibernate"],
  ["wolf", "howl"],
  ["fox", "sneak"],
];

// Food themed pairs
export const foodPairs: [string, string][] = [
  ["pizza", "slice"],
  ["burger", "patty"],
  ["sandwich", "bread"],
  ["salad", "lettuce"],
  ["soup", "bowl"],
  ["pasta", "noodle"],
  ["rice", "grain"],
  ["bread", "toast"],
  ["cheese", "melt"],
  ["milk", "pour"],
  ["juice", "squeeze"],
  ["coffee", "brew"],
  ["tea", "steep"],
  ["cake", "frosting"],
  ["cookie", "bake"],
  ["ice", "cream"],
  ["chocolate", "sweet"],
  ["apple", "crunch"],
  ["banana", "peel"],
  ["orange", "juice"],
];

// Movies themed pairs
export const moviesPairs: [string, string][] = [
  ["action", "explosion"],
  ["comedy", "laugh"],
  ["drama", "emotion"],
  ["horror", "scare"],
  ["romance", "love"],
  ["thriller", "suspense"],
  ["sci-fi", "future"],
  ["fantasy", "magic"],
  ["western", "cowboy"],
  ["musical", "sing"],
  ["documentary", "real"],
  ["animation", "cartoon"],
  ["sequel", "continue"],
  ["prequel", "before"],
  ["remake", "again"],
  ["trailer", "preview"],
  ["credits", "end"],
  ["director", "vision"],
  ["actor", "perform"],
  ["script", "dialogue"],
];

// Sports themed pairs
export const sportsPairs: [string, string][] = [
  ["football", "touchdown"],
  ["basketball", "hoop"],
  ["soccer", "goal"],
  ["tennis", "racket"],
  ["golf", "club"],
  ["baseball", "bat"],
  ["hockey", "puck"],
  ["swimming", "pool"],
  ["running", "track"],
  ["cycling", "bike"],
  ["boxing", "punch"],
  ["wrestling", "pin"],
  ["volleyball", "spike"],
  ["badminton", "shuttlecock"],
  ["cricket", "wicket"],
  ["rugby", "tackle"],
  ["skiing", "slope"],
  ["surfing", "wave"],
  ["climbing", "rope"],
  ["archery", "target"],
];

// Original random pairs
export const randomPairs: [string, string][] = [
  ["library", "scholar"],
  ["volcano", "pressure"],
  ["harbor", "anchor"],
  ["temple", "ritual"],
  ["subway", "tunnel"],
  ["cinnamon", "warmth"],
  ["avocado", "smooth"],
  ["espresso", "pulse"],
  ["honey", "gold"],
  ["cheese", "aging"],
  ["compass", "needle"],
  ["mirror", "twin"],
  ["lantern", "wander"],
  ["book", "story"],
  ["hourglass", "patience"],
  ["whisper", "air"],
  ["dreaming", "float"],
  ["climbing", "height"],
  ["forgiving", "release"],
  ["escaping", "distance"],
  ["cathedral", "echo"],
  ["alley", "brick"],
  ["oasis", "relief"],
  ["garden", "growth"],
  ["attic", "dust"],
  ["museum", "memory"],
  ["bridge", "span"],
  ["station", "pause"],
  ["market", "crowd"],
  ["theater", "mask"],
  ["river", "flow"],
  ["island", "solitude"],
  ["canyon", "depth"],
  ["tavern", "noise"],
  ["train", "motion"],
  ["castle", "stone"],
  ["storm", "charge"],
  ["meadow", "still"],
  ["forest", "hidden"],
  ["harvest", "return"],
  ["shadow", "trace"],
  ["echo", "repeat"],
  ["ember", "after"],
  ["frost", "quiet"],
  ["horizon", "edge"],
  ["twilight", "fade"],
  ["gravity", "pull"],
  ["silence", "absence"],
  ["motion", "continuum"],
  ["memory", "trace"],
  ["faith", "leap"],
  ["fortune", "chance"],
  ["karma", "return"],
  ["origin", "birth"],
  ["destiny", "path"],
  ["serenity", "stillness"],
  ["chaos", "fracture"],
  ["revolt", "shift"],
  ["reflection", "mirror"],
  ["pulse", "beat"],
  ["flame", "rise"],
  ["breeze", "soft"],
  ["ocean", "depth"],
  ["stone", "weight"],
  ["glass", "fragile"],
  ["thread", "link"],
  ["mask", "hidden"],
  ["chime", "signal"],
  ["key", "turn"],
  ["anchor", "steady"],
  ["cloak", "veil"],
  ["vessel", "contain"],
  ["map", "path"],
  ["gate", "threshold"],
  ["tower", "height"],
  ["sanctuary", "safe"],
  ["desert", "barren"],
  ["labyrinth", "maze"],
  ["field", "open"],
  ["candle", "wax"],
  ["quill", "scribe"],
  ["ink", "mark"],
  ["clock", "tick"],
  ["window", "view"],
  ["feather", "light"],
  ["seed", "begin"],
  ["shell", "hollow"],
  ["chain", "bind"],
  ["crown", "rule"],
  ["veil", "cover"],
  ["sword", "cut"],
  ["shield", "guard"],
  ["flute", "breath"],
  ["harp", "string"],
  ["drum", "rhythm"],
  ["telescope", "distant"],
  ["camera", "frame"],
  ["record", "track"],
  ["typewriter", "click"],
  ["canvas", "surface"],
  ["palette", "blend"],
  ["sculpture", "shape"],
  ["painting", "color"],
  ["statue", "still"],
  ["festival", "joy"],
  ["ceremony", "symbol"],
  ["journey", "path"],
  ["escape", "break"],
  ["flight", "sky"],
  ["growth", "expand"],
  ["balance", "center"],
  ["transit", "move"],
  ["creation", "birth"],
  ["destruction", "ruin"],
  ["betrayal", "trust"],
  ["loyalty", "bond"],
  ["freedom", "open"],
  ["fear", "tremor"],
  ["truth", "clear"],
  ["illusion", "veil"],
  ["revelation", "unveil"],
  ["vision", "sight"],
  ["mirage", "fake"],
  ["ripple", "small"],
  ["spark", "start"],
  ["signal", "call"],
  ["tide", "pull"],
  ["orbit", "cycle"],
  ["drift", "slow"],
  ["voyage", "travel"],
  ["arrival", "close"],
  ["departure", "away"],
  ["ascent", "rise"],
  ["fall", "drop"],
  ["rescue", "save"],
  ["pursuit", "chase"],
  ["hiding", "quiet"],
  ["forgiveness", "mercy"],
  ["revenge", "burn"],
  ["awakening", "aware"],
  ["sleep", "rest"],
  ["future", "ahead"],
  ["yesterday", "past"],
  ["tomorrow", "next"],
  ["dream", "mind"],
  ["nightmare", "fear"],
  ["laughter", "light"],
  ["sorrow", "heavy"],
  ["hope", "reach"],
  ["doubt", "unclear"],
  ["promise", "bond"],
  ["secret", "hidden"],
  ["ritual", "repeat"],
  ["song", "melody"],
  ["language", "symbol"],
  ["word", "sound"],
  ["light", "beam"],
  ["smoke", "after"],
  ["ice", "still"],
  ["dust", "settle"],
  ["rain", "fall"],
  ["snow", "quiet"],
  ["lightning", "flash"],
  ["moon", "orbit"],
  ["sun", "core"],
  ["star", "distant"],
  ["planet", "circle"],
  ["comet", "flare"],
  ["galaxy", "vast"],
  ["universe", "all"],
  ["infinity", "beyond"],
  ["moment", "blink"],
  ["eternity", "endless"],
  ["cycle", "loop"],
  ["season", "turn"],
  ["bloom", "open"],
  ["root", "origin"],
  ["branch", "extend"],
  ["petal", "soft"],
  ["leaf", "green"],
  ["fruit", "sweet"],
  ["bone", "structure"],
  ["wing", "flight"],
  ["claw", "grip"],
  ["scale", "pattern"],
  ["horn", "curve"],
  ["voice", "tone"],
  ["gesture", "motion"],
  ["pattern", "repeat"],
  ["order", "align"],
];

// Function to get word pairs based on theme
export function getWordPairsByTheme(theme: ThemeKey): [string, string][] {
  switch (theme) {
    case "clashroyale":
      return clashRoyalePairs;
    case "fortnite":
      return fortnitePairs;
    case "teachers":
      return teachersPairs;
    case "animals":
      return animalsPairs;
    case "food":
      return foodPairs;
    case "movies":
      return moviesPairs;
    case "sports":
      return sportsPairs;
    case "random":
    default:
      return randomPairs;
  }
}

// Backward compatibility - keep the original export
export const impostorPairs = randomPairs;
